### ISSUE TITLE
This is absolutely brilliant, a pure-Java HTTP3/QUIC and TLS stack from the ground up. Do you have any benchmarks?

### ISSUE THREAD

**Issue by GavinRay97** [ptrd/flupke#2]
As the title says, monumentally impressed by the combination of `kwik`, `agent15`, `qpack`, and `flupke`.

Curious if you've run any benchmarks against the HTTP 3 server, would be interesting to see.

**Comment by ptrd** [comment]
Hi,
Thanks for the feedback! 😊

I haven't run any benchmarks myself, but the interop tests (https://interop.seemann.io/) contain some measurements (scroll down on the results page). Kwik is not the best (fastest) in this league. I have some ideas what could be the cause, but would need to run more experiments to validate these assumptions.
