### ISSUE TITLE
Issues when combining openapi generated code with flupke

### ISSUE THREAD

**Issue by AlexanderSchuetz97** [ptrd/flupke#4]
Hello,

I am trying to use openapi generator to generate a rest client from a openapi json/yaml schema and use the resulting code with flupke.
Not to bother you with the details of this setup but generally the generator generates code that only uses the java.net.http.HttpClient.
It does not really care that the client actually speaks http or where it comes from. It just cares that the client implements the HttpClient interface.

I dont think this is rare/edge case as I believe most rest dev's nowadays use openapi or soap when speaking anything remotely http. Most of the tooling relies on code generation. OpenAPI's code generators is one of the most popular ones.

Dropping in Flupke into this was not really a big deal and seamed super smooth at first. (The generated code works really well with http 1.1 and http2)

Unfortunately your implementation of HttpClient does not follow the interface in some regards. 
I do not list them in order of importance but rather in order of encountering them.

1. You don't implement HttpClient.Builder.sslContext. Your impl is a noop.
This is not yet an issue for me yet, but will be a issue since this method is needed to support client side certificates.
It would be nice to have this as a feature in the future. It would also make it identical to http 1.1 & 2 clients to supply the
Trust everything Trustmanager. Thats how I actually noticed this since I tried to install the I trust self signed certs TrustManager via
SSLContext only to realize that it was ignored. I found your custom non Interface method to disable cert checks later and I am using that now.

2. You do not check that a BodyPublisher actually has content.
The method BodyPublisher.contentLength() states that if the result is 0 then no request body is present. The code generator populates
request objects with HttpRequest.Builder like this

localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());

This fails your check in your class Http3Connection.java line 152.
Your check is:
if (request.bodyPublisher().isPresent()) {
-> Send the body
}

It should be:
if (request.bodyPublisher().isPresent() && request.bodyPublisher().get().contentLength() != 0) {
-> Send the body
}

Not doing this causes Jetty Server (using QUICHE) to reset the connection.

To carry on with my tests I changed this locally and recompiled your library.

3. You do not support HttpResponse.BodyHandlers.ofInputStream() properly.
The code generator uses HttpResponse.BodyHandlers.ofInputStream() for every request.

The gist is that HttpResponse.BodyHandlers.ofInputStream expects that HttpClient.send will return 
instantly once the Http Headers are read. Your implementation does not do this. Internally the BodySubscriber has a 
BlockingQueue that can store a finite number of calls to onNext. Once the Queue is full, onNext throws an exception since it expects a consumer to actively read from the stream. It is impossible to consume the stream since your impl of HttpClient.send only returns 
after onComplete() is called. It also does not help that you also appear to call onNext with empty buffers, this just fills the queue faster.

I do realize why you are doing this since apparently Http3 supports trailing headers and HttpResponse has no way of receiving trailing headers. 

May I suggest adding a custom flag to 
Http3ClientBuilder to allow us to "ignore" trailing headers? Jetty Server (using QUICHE) never sends them anyways.

If Trailing headers are ignored then could you return a HttpResponse once BodySubscriber.getBody() (a CompletionStage) completes?
This is the behavior of the default HttpClient. I am sure this will fix a whole bunch of other custom BodySubscribers that rely on this behavior. After returning you will probably have to transition receiving further frames to a background worker thread. 
(Or perhaps you could just always do all the work in a background thread?)

In addtion obmitting calls to onNext if the ByteBuffer is empty will also be very beneficial.
What would also help is to bundle a bunch of Quiche Frames together into a Collection and only call BodySubscriber.onNext
when a bunch of Frames having at least ~64kb of data are allocated. This would also prevent the queue from filling before the async consumer can drain it. Obvieusly the onNext method also has to be called with all "cached" frames before the onComplete method is called.

The minimum required code to trigger this "bug" is:
HttpClient client = ....
HttpRequest.Builder requestBuilder = ...
HttpResponse<InputStream> send = client.send(requestBuilder.build(), HttpResponse.BodyHandlers.ofInputStream());
byte[] message = send.body().readAllBytes();

My test ran once again against a Jetty Server (using QUICHE) on localhost. The response body has about 200 bytes.
curl compiled with http3 support and BodyHandlers.ofByteArray were able to receive the body.

I would be interested to hear your opinion on this.
If you are willing to accept a pull request with the changes I propose for issue 3 then I will start the work to implement this.

Sincerely
Alexander Schütz

**Comment by AlexanderSchuetz97** [comment]
It appears I have too much time...

Heres a patch that fixes my issues. I ended up not doing the 64KB aggregation thing mentioned in my comment yet. 
[fix.patch](https://github.com/ptrd/flupke/files/12307635/fix.patch)

Its based on master 03d300f923f2ff14f8a8e310a0848e5ce360e5d6
Just download it and run "git am fix.patch" to see my suggested changes.

Sincerely
Alexander Schütz

**Comment by ptrd** [comment]
Hi,

Thanks a lot for your feedback and contribution! I will certainly look into it, but don' have much time at the moment, so don't be disappointed when it takes a while ;-).

A pratical issue: when applying the patch, git responds with an error saying "fatal: empty ident name (for <>) not allowed". Any idea how to solve or work around this?

Cheers
Peter

**Comment by AlexanderSchuetz97** [comment]
Hi Peter, 

To apply the patch you can use "git apply fix2.patch"
This will however not actually add a commit, just add my changes to your working tree. (You will have to make the commit yourself)

I believe I forgot to add my author information to the patch, That's why it complains.
Sorry for that, I don't normally use git patches.

Don't worry I have realized that you do not have much time even before opening this issue.
This patch is sufficient for me to use http3 at least in a "experimental" capacity (since the Jetty Server Quiche adapter is also considered experimental, so I dont intend to use it in Prod yet). So if you have time to look at this in i don't know the next 6 months (or more) to fix it properly then that would be all good for me. 

Sincerely 
Alexander Schütz

**Comment by ptrd** [comment]
I started with (2) "You do not check that a BodyPublisher actually has content." / "Not doing this causes Jetty Server (using QUICHE) to reset the connection."

I cannot reproduce this. I installed Jetty 11, enabled http3, modified Sample.java to use an empty body publisher like this
```
        HttpRequest request = HttpRequest.newBuilder()
                .uri(serverUrl)
                .method("GET", HttpRequest.BodyPublishers.noBody())
                .header("User-Agent", "Flupke http3 library")
                .timeout(Duration.ofSeconds(10))
                .build();
```

Works likes charm:
```
Got HTTP response (GET https://localhost:8444) 200
-   HTTP headers: 
--  accept-ranges	[bytes]
--  content-length	[3471]
--  content-type	[text/html]
--  Expires	[Thu, 01 Jan 1970 00:00:00 GMT]
--  Last-Modified	[Fri, 18 Aug 2023 14:22:53 GMT]
--  server	[Jetty(11.0.15)]
--  set-cookie	[visited=yes]
-   HTTP body (3471 bytes, 11 B/s):
<html xmlns=\ "http://www.w3.org/1999/xhtml\" xml:lang=\"en\">
<head>
<META http-equiv="Pragma" content="no-cache">
<META http-equiv="Cache-Control" content="no-cache,no-store">
<META HTTP-EQUIV="Content-Script-Type" CONTENT="text/javascript">
<title>Welcome to Jetty-11</title>
(...)
```

**Comment by ptrd** [comment]
@AlexanderSchuetz97 , can you create a separate issue for (3)? You can just copy the text from above concerning (3). I'd like to have a separate issue for it to avoid confusion and I would like you to be the author of it..... thanks in advance.

**Comment by AlexanderSchuetz97** [comment]
Hello,
you are correct. Issue 2 cant be reproduced by me anymore. However modifying the IF is a good idea anyways.
I am unsure why I reported this but modifying the if statement did fix something. I just cant reproduce exactly what anymore.

Anyways the javadoc of BodyPublisher is pretty clear that the check should be done.
![image](https://github.com/ptrd/flupke/assets/66277940/950e3ae6-281a-429c-8742-4edf58516d0b)

I have also attached a full minimal testproject as a zip file. I have tested it with Eclipse Temurin Java 17.
This testproject includes basic openapi generation from a endpoint. It generates the client code and then 
starts a jetty and uses flupke to try and connect to it. Issue 3 can be reproduced with it. See the FLTest.java file

Flupke.jar is loaded by URLClassloader so to "update/replace" flupke in this testproject simply replace flupke.jar in the project root.
I am running this project in IntelliJ
Since this is just a testproject I did not really bother making a proper gradle build (sorry)
To run simply execute "gradle test"
To build run "gradle clean genCode"
"gradle clean build" is bricked in this project :/

Here is the zip:
[flupke-jetty-bug-demonstration.zip](https://github.com/ptrd/flupke/files/12387618/flupke-jetty-bug-demonstration.zip)


I do not understand what you mean by creating a seperate issue? 
Do you want me to create a pull request with my patch?

Sincerely
Alexander Schütz

**Comment by AlexanderSchuetz97** [comment]
Hello,

I think we can call Issue 2 solved then. It must have been some other issue that was causing this or me misreading some exceptions. Anyways I agree with out that this does not make it fail.

I will close this issue here and open
 
1 for the SSLContent via HttpBuilder
1 for the support of HttpResponse.BodyHandlers.ofInputStream()
