### ISSUE TITLE
HttpResponse.BodyHandlers.ofInputStream() does not work with Flupke. (Causes Exception)

### ISSUE THREAD

**Issue by AlexanderSchuetz97** [ptrd/flupke#6]
The minimum required code to trigger this "bug" is:
HttpClient client = ....
HttpRequest.Builder requestBuilder = ...
HttpResponse send = client.send(requestBuilder.build(), HttpResponse.BodyHandlers.ofInputStream());
byte[] message = send.body().readAllBytes();

I am testing again a Jetty 11.0.15 Server (using QUICHE) on localhost. The response body has about 200 bytes.
curl compiled with http3 support and BodyHandlers.ofByteArray were able to receive the body.

A minimum test project that can be used to trigger/replicate the bug can be found here:
https://github.com/ptrd/flupke/files/12387618/flupke-jetty-bug-demonstration.zip

To build the test project run
"gradle clean genCode"

To runt he test run:
 "gradle test"

Flupke.jar is loaded by URLClassloader so to "update/replace" flupke in this testproject simply replace flupke.jar in the project root.

A experimental "fix" can be found in this patch
https://github.com/ptrd/flupke/files/12307686/fix2.patch
to apply the fix run "git apply fix2.patch"

**Comment by ptrd** [comment]
Fixed.
